<form method="POST">
    <div class="mb-3">
        <label for="email" class="form-label white">Email address</label>
        <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="password">
    </div>
    <div class="mt-12 mb-3 form-check">
        <label class="form-check-label" for="receive_news">Check me out</label>
        <input type="checkbox" name="receive_news" class="form-check-input" id="receive_news">
    </div>
    <button type="submit" class="btn px-4 btn-primary">Submit</button>
</form>